name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven and Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Release on Tag
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TRAVIS_TAG: "${{ steps.get_version.outputs.version }}"
        run: |
          echo "${{github.ref}} ${{env.TRAVIS_TAG}}"
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
          echo "${{ steps.get_version.outputs.version }}"
